export const UPDATE_RECIPES = "UPDATE_RECIPES";
export const REMOVE_RECIPES = "REMOVE_RECIPES";
export const SET_CURRENT_RECIPES = "SET_CURRENT_RECIPES";
export const ADD_RECIPES = "ADD_RECIPES";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
